version: "3"

services:
  #MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 4000:3000
    environment:
      APP_NAME: remote-patient-javascript
      PORT: 3000
      DB_URI: mongodb+srv://${{env.MONGO_USER}}:${{env.MONGO_PASSKEY}}@ewriter.y9z37mo.mongodb.net/HealthChecker
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
